/*==============================================================*/
/* Insert table: CCR.CCRTB037_TIPO_SITUACAO                     */
/*==============================================================*/
INSERT INTO CCR.CCRTB037_TIPO_SITUACAO (NU_TIPO_SITUACAO, NO_TIPO_SITUACAO) VALUES (4, 'ARQUIVO');
INSERT INTO CCR.CCRTB037_TIPO_SITUACAO (NU_TIPO_SITUACAO, NO_TIPO_SITUACAO) VALUES (5, 'CANAL');


/*==============================================================*/
/* Insert table: CCR.CCRTB014_SITUACAO                          */
/*==============================================================*/
INSERT INTO CCR.CCRTB014_SITUACAO (NU_TIPO_SITUACAO, NU_SITUACAO, DE_SITUACAO) VALUES (4, 1, 'INICIAL');
INSERT INTO CCR.CCRTB014_SITUACAO (NU_TIPO_SITUACAO, NU_SITUACAO, DE_SITUACAO) VALUES (4, 2, 'PROCESSADO');
INSERT INTO CCR.CCRTB014_SITUACAO (NU_TIPO_SITUACAO, NU_SITUACAO, DE_SITUACAO) VALUES (4, 3, 'PROCESSAMENTO COM ERRO');
INSERT INTO CCR.CCRTB014_SITUACAO (NU_TIPO_SITUACAO, NU_SITUACAO, DE_SITUACAO) VALUES (4, 4, 'NÃO PROCESSADO');

INSERT INTO CCR.CCRTB014_SITUACAO (NU_TIPO_SITUACAO, NU_SITUACAO, DE_SITUACAO) VALUES (5, 1, 'ATIVO');
INSERT INTO CCR.CCRTB014_SITUACAO (NU_TIPO_SITUACAO, NU_SITUACAO, DE_SITUACAO) VALUES (5, 2, 'INATIVO');
