

/*==============================================================*/
/* Table: CCRTB039_AVALIACAO_RISCO                                    */
/*==============================================================*/

CREATE TABLE CCR.CCRTB039_AVALIACAO_RISCO  ( 
	NU_AVALIACAO_RISCO          	NUMBER(19) NOT NULL,
	NU_OPERACAO_PRODUTO         	NUMBER(19) NOT NULL,
	NO_PRODUTO_SIRIC            	VARCHAR2(50) NULL,
	VR_MAXIMO_PRESTACAO         	NUMBER(14,2) NOT NULL,
	DT_INICIO_VALIDADE_AVALIACAO	DATE NOT NULL,
	DT_FIM_VALIDADE_AVALIACAO   	DATE NOT NULL,
	VR_MAXIMO_EMPRESTIMO        	NUMBER(14,2) NULL,
	DE_RESULTADO_AVALIACAO      	VARCHAR2(255) NULL,
	PZ_MAXIMO_EMPRESTIMO        	NUMBER(5) NOT NULL,
	IC_AVALIACAO_MANUAL         	CHAR(1) DEFAULT 'N' NULL,
	IN_RATING_AVALIACAO         	NUMBER(3) NOT NULL,
	IC_BLOQUEIO_ALCADA          	CHAR(1) NOT NULL,
	CO_RESULTADO                	VARCHAR2(3) NOT NULL,
	DT_GERACAO                  	DATE NOT NULL,
	CONSTRAINT PK_CCRTB039 PRIMARY KEY(NU_AVALIACAO_RISCO)
);
ALTER TABLE CCR.CCRTB039_AVALIACAO_RISCO
	ADD ( CONSTRAINT CC_CCRTB039_2
	CHECK (IC_BLOQUEIO_ALCADA in ('S','N'))
	 );
ALTER TABLE CCR.CCRTB039_AVALIACAO_RISCO
	ADD ( CONSTRAINT CC_CCRTB039_1
	CHECK (IC_AVALIACAO_MANUAL is null or (IC_AVALIACAO_MANUAL in ('S','N')))
	);


/*==============================================================*/
/* Table: CCRTB013_CONTRATO                                     */
/*==============================================================*/
CREATE TABLE CCR.CCRTB013_CONTRATO  ( 
	NU_CONTRATO                	NUMBER(19) NOT NULL,
	NU_UNIDADE_MOVIMENTO       	NUMBER(19) NOT NULL,
	NU_NATURAL_MOVIMENTO       	NUMBER(19) NOT NULL,
	NU_CPF                     	NUMBER(11) NOT NULL,
	NU_COCLI                   	NUMBER(19) NOT NULL,
	NU_RIC                     	NUMBER(15) NULL,
	NU_BENEFICIO               	NUMBER(8) NULL,
	NU_CONTRATO_APLICACAO      	NUMBER(19) NOT NULL,
	VR_LIQUIDO_CONTRATO        	NUMBER(11,2) NOT NULL,
	VR_PRESTACAO               	NUMBER(8,2) NOT NULL,
	PZ_VIGENCIA_CONTRATO       	NUMBER(4) NOT NULL,
	VR_CONTRATO                	NUMBER(11,2) NOT NULL,
	DT_LIBERACAO_CREDITO       	DATE NOT NULL,
	VR_IOF                     	NUMBER(8,2) NOT NULL,
	PC_TAXA_JURO_CONTRATO      	NUMBER(8,5) NOT NULL,
	PC_CET_MENSAL              	NUMBER(8,5) NOT NULL,
	PC_CET_ANUAL               	NUMBER(8,5) NOT NULL,
	DT_BASE_CALCULO            	DATE NOT NULL,
	DT_VNCMO_PRIMEIRA_PRESTACAO	DATE NOT NULL,
	QT_DIA_JURO_ACERTO         	NUMBER(6) NULL,
	VR_JURO_ACERTO             	NUMBER(8,2) NULL,
	VR_SEGURO_PRESTAMISTA      	NUMBER(11,2) NULL,
	PC_TAXA_SEGURO             	NUMBER(8,5) NOT NULL,
	NU_BANCO_CONTA_CREDITO     	NUMBER(4) NULL,
	NU_AGENCIA_CONTA_CREDITO   	NUMBER(5) NULL,
	NU_OPERACAO_CONTA_CREDITO  	NUMBER(3) NULL,
	NU_CONTA_CREDITO           	NUMBER(8) NULL,
	NU_DV_CONTA_CREDITO        	NUMBER(1) NULL,
	IC_TIPO_CREDITO            	NUMBER(1) NOT NULL,
	DT_CONTRATO                	DATE NOT NULL,
	PC_ALIQUOTA_BASICA         	NUMBER(8,5) NOT NULL,
	PC_ALIQUOTA_COMPLEMENTAR   	NUMBER(8,5) NOT NULL,
	NU_AVALIACAO               	NUMBER(19) NOT NULL,
	DH_ULTIMA_SITUACAO         	TIMESTAMP(6) NULL,
	NU_SITUACAO                	NUMBER(5) NULL,
	NU_TIPO_SITUACAO           	NUMBER(5) NULL,
	NU_CONVENIO                	NUMBER(5) NULL,
	NU_BANCO_CONTA_DEBITO      	NUMBER(4) NULL,
	NU_AGENCIA_CONTA_DEBITO    	NUMBER(5) NULL,
	NU_OPERACAO_CONTA_DEBITO   	NUMBER(3) NULL,
	NU_CONTA_DEBITO            	NUMBER(8) NULL,
	NU_DV_CONTA_DEBITO         	NUMBER(1) NULL,
	VR_CET_MENSAL              	NUMBER(8,5) NULL,
	VR_CET_ANUAL               	NUMBER(8,5) NULL,
	PC_CET_JURO_ACERTO         	NUMBER(8,5) NULL,
	PC_CET_CAPITAL             	NUMBER(8,5) NULL,
	PC_CET_IOF                 	NUMBER(8,5) NULL,
	PC_CET_SEGURO              	NUMBER(8,5) NULL,
	VR_BRUTO_BENEFICIO         	NUMBER(15,2) NULL,
	VR_LIQUIDO_BENEFICIO       	NUMBER(15,2) NULL,
	PC_TAXA_JURO_ANUAL         	NUMBER(8,5) NULL,
	IC_EMPREGADO_TEMPORARIO    	CHAR(1) NULL,
	CO_USUARIO                 	CHAR(8) NULL,
	DT_VENCIMENTO              	DATE NULL,
	IC_SEGURO_PRESTAMISTA      	CHAR(1) NULL,
	DT_COMPETENCIA             	DATE NULL,
	IC_RECEBE_SALARIO_CAIXA    	CHAR(1) NULL,
	IC_TIPO_SIMULACAO          	CHAR(1) NULL,
	NU_ORGAO_MILITAR           	NUMBER(6) NULL,
	QT_EMPREGADO               	NUMBER(5) NULL,
	DD_BENEFICIO               	NUMBER(2) NULL,
	NU_CNPJ_FONTE_PAGADORA     	NUMBER(14) NULL,
	VR_TOTAL_CONTRATO          	NUMBER(11,2) NULL,
	CO_MATRICULA_CLIENTE       	VARCHAR2(100) NULL,
	NU_AGENCIA_CONCESSORA      	NUMBER(5) NULL,
	DD_VENCIMENTO_PRESTACAO    	NUMBER(2) NULL,
	CONSTRAINT PK_CCRTB013 PRIMARY KEY(NU_CONTRATO)
);
ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB013_5
	CHECK (IC_TIPO_SIMULACAO is null or (IC_TIPO_SIMULACAO in ('P','V')))
	 );
ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB013_4
	CHECK (IC_RECEBE_SALARIO_CAIXA is null or (IC_RECEBE_SALARIO_CAIXA in ('S','N')))
	 );
ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB013_3
	CHECK (IC_SEGURO_PRESTAMISTA is null or (IC_SEGURO_PRESTAMISTA in ('S','N')))
	 );
ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB013_2
	CHECK (IC_EMPREGADO_TEMPORARIO is null or (IC_EMPREGADO_TEMPORARIO in ('S','N')))
	 );
ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB013_1
	CHECK (IC_TIPO_CREDITO in (1,2))
	 );





ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB013_CCRTB039
	FOREIGN KEY(NU_AVALIACAO)
	REFERENCES CCR.CCRTB039_AVALIACAO_RISCO(NU_AVALIACAO_RISCO)
	 );
ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB013_CCRTB014
	FOREIGN KEY(NU_SITUACAO, NU_TIPO_SITUACAO)
	REFERENCES CCR.CCRTB014_SITUACAO(NU_SITUACAO, NU_TIPO_SITUACAO)
	 );
ALTER TABLE CCR.CCRTB013_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB013_CCRTB001
	FOREIGN KEY(NU_CONVENIO)
	REFERENCES CCR.CCRTB001_CONVENIO(NU_CONVENIO)
	 );


/*==============================================================*/
/* Table: CCRTB038_HISTORICO_SITUACAO                            */
/*==============================================================*/

CREATE TABLE CCR.CCRTB038_HISTORICO_SITUACAO  ( 
	NU_HISTORICO_SITUACAO	NUMBER(19) NOT NULL,
	NU_CONTRATO          	NUMBER(19) NOT NULL,
	NU_SITUACAO          	NUMBER(5) NULL,
	NU_TIPO_SITUACAO     	NUMBER(5) NULL,
	DT_SITUACAO_CONTRATO 	DATE NOT NULL,
	CO_USUARIO           	CHAR(8) NOT NULL,
	CONSTRAINT PK_CCRTB038 PRIMARY KEY(NU_HISTORICO_SITUACAO)
);
ALTER TABLE CCR.CCRTB038_HISTORICO_SITUACAO
	ADD ( CONSTRAINT FK_CCRTB038_FK_CCRTB0_CCRTB014
	FOREIGN KEY(NU_SITUACAO, NU_TIPO_SITUACAO)
	REFERENCES CCR.CCRTB014_SITUACAO(NU_SITUACAO, NU_TIPO_SITUACAO)
	 );
ALTER TABLE CCR.CCRTB038_HISTORICO_SITUACAO
	ADD ( CONSTRAINT FK_CCRTB038_CCRTB013
	FOREIGN KEY(NU_CONTRATO)
	REFERENCES CCR.CCRTB013_CONTRATO(NU_CONTRATO)
	 );
	
create index CCR.CCR2I038 on CCR.CCRTB038_HISTORICO_SITUACAO (
   NU_CONTRATO ASC
);


/*==============================================================*/
/* Table: CCRTB012_SIMULACAO_CONTRATO                                    */
/*==============================================================*/

CREATE TABLE CCR.CCRTB012_SIMULACAO_CONTRATO  ( 
	NU_SIMULACAO_CONTRATO      	NUMBER(18) NOT NULL,
	NU_CONVENIO                	NUMBER(5) NULL,
	NU_CPF                     	NUMBER(11) NULL,
	NU_BENEFICIO               	NUMBER(11) NULL,
	VR_MARGEM                  	NUMBER(8,2) NOT NULL,
	VR_LIQUIDO_CONTRATO        	NUMBER(11,2) NOT NULL,
	VR_PRESTACAO               	NUMBER(8,2) NOT NULL,
	VR_CONTRATO                	NUMBER(11,2) NOT NULL,
	PZ_CONTRATO                	NUMBER(5) NOT NULL,
	DT_LIBERACAO_CREDITO       	DATE NOT NULL,
	DT_BASE_CALCULO            	DATE NOT NULL,
	DT_VNCMO_PRIMEIRA_PRESTACAO	DATE NOT NULL,
	DT_VENCIMENTO              	DATE NULL,
	QT_DIA_JURO_ACERTO         	NUMBER(5) NULL,
	VR_JURO_ACERTO             	NUMBER(8,2) NULL,
	IC_SEGURO_PRESTAMISTA      	CHAR(1) NOT NULL,
	VR_SEGURO_PRESTAMISTA      	NUMBER(11,2) NULL,
	VR_IOF                     	NUMBER(8,2) NOT NULL,
	PC_CET_MENSAL              	NUMBER(8,5) NOT NULL,
	PC_CET_ANUAL               	NUMBER(8,5) NOT NULL,
	PC_TAXA_JURO_SIMULACAO     	NUMBER(8,5) NULL,
	PC_TAXA_SEGURO             	NUMBER(8,5) NULL,
	PC_ALIQUOTA_BASICA         	NUMBER(8,5) NULL,
	PC_ALIQUOTA_COMPLEMENTAR   	NUMBER(8,5) NULL,
	DT_SIMULACAO               	DATE NOT NULL,
	DE_AUDITORIA_SIMULACAO     	CLOB NULL,
	CONSTRAINT PK_CCRTB012 PRIMARY KEY(NU_SIMULACAO_CONTRATO)
);
ALTER TABLE CCR.CCRTB012_SIMULACAO_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB012_1
	CHECK (IC_SEGURO_PRESTAMISTA in ('S','N'))
	 );
ALTER TABLE CCR.CCRTB012_SIMULACAO_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB001_CCRTB12
	FOREIGN KEY(NU_CONVENIO)
	REFERENCES CCR.CCRTB001_CONVENIO(NU_CONVENIO)
	 );


create index CCR.CCR2I012 on CCR.CCRTB012_SIMULACAO_CONTRATO (
   DT_SIMULACAO ASC
);








/*==============================================================*/
/* Table: CCRTB050_AUTORIZACAO_CONTRATO                                  */
/*==============================================================*/
CREATE TABLE CCR.CCRTB050_AUTORIZACAO_CONTRATO  ( 
	NU_SEQ_AUTORIZACAO     	NUMBER(19) NOT NULL,
	NU_CONTRATO            	NUMBER(19) NULL,
	NU_SITUACAO_CONTRATO   	NUMBER(19) NULL,
	IC_TIPO_AUTORIZACAO    	CHAR(1) NULL,
	IC_SITUACAO_AUTORIZACAO	CHAR(1) NULL,
	DE_JUSTIFICATIVA       	VARCHAR2(255) NULL,
	CO_USUARIO_AUTORIZACAO 	CHAR(8) NULL,
	TS_AUTORIZACAO         	TIMESTAMP(6) NULL,
	CONSTRAINT PK_CCRTB050 PRIMARY KEY(NU_SEQ_AUTORIZACAO)
);
ALTER TABLE CCR.CCRTB050_AUTORIZACAO_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB050_2
	CHECK (IC_SITUACAO_AUTORIZACAO is null or (IC_SITUACAO_AUTORIZACAO in ('A','N')))
	 );
ALTER TABLE CCR.CCRTB050_AUTORIZACAO_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB050_1
	CHECK (IC_TIPO_AUTORIZACAO is null or (IC_TIPO_AUTORIZACAO in ('G','C')))
	 );
ALTER TABLE CCR.CCRTB050_AUTORIZACAO_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB050_CCRTB013
	FOREIGN KEY(NU_CONTRATO)
	REFERENCES CCR.CCRTB013_CONTRATO(NU_CONTRATO)
	 );
ALTER TABLE CCR.CCRTB050_AUTORIZACAO_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB038_CCRTB050
	FOREIGN KEY(NU_SITUACAO_CONTRATO)
	REFERENCES CCR.CCRTB038_HISTORICO_SITUACAO(NU_HISTORICO_SITUACAO)
	 );


/*==============================================================*/
/* Table: CCRTB070_TIPO_MODELO                               */
/*==============================================================*/
CREATE TABLE CCR.CCRTB070_TIPO_MODELO  ( 
	NU_TIPO_MODELO       	NUMBER(19) NOT NULL,
	NU_SISTEMA           	NUMBER(19) NULL,
	NO_TIPO_MODELO       	VARCHAR2(50) NOT NULL,
	DE_MODELO_HTML_PADRAO	CLOB NULL,
	CONSTRAINT PK_CCRTB070 PRIMARY KEY(NU_TIPO_MODELO)
);



/*==============================================================*/
/* Table: CCRTB071_MODELO_CONTRATO                                    */
/*==============================================================*/

CREATE TABLE CCR.CCRTB071_MODELO_CONTRATO  ( 
	NU_MODELO              	NUMBER(19) NOT NULL,
	NU_TIPO_MODELO         	NUMBER(19) NULL,
	NO_MODELO              	VARCHAR2(255) NOT NULL,
	DT_INICIO_VIGENCIA     	DATE NOT NULL,
	DT_FIM_VIGENCIA        	DATE NULL,
	DE_MODELO_HTML_CONTRATO	CLOB NULL,
	IC_STATUS              	CHAR(1) NOT NULL,
	NU_VERSAO              	NUMBER(4) NULL,
	CO_USUARIO             	CHAR(8) NOT NULL,
	DT_INCLUSAO            	DATE NOT NULL,
	DT_ATUALIZACAO         	DATE NOT NULL,
	CONSTRAINT PK_CCRTB071 PRIMARY KEY(NU_MODELO)
);
ALTER TABLE CCR.CCRTB071_MODELO_CONTRATO
	ADD ( CONSTRAINT CC_CCRTB071_1
	CHECK (IC_STATUS in ('A','I'))
	 );
ALTER TABLE CCR.CCRTB071_MODELO_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB071_CCRTB070
	FOREIGN KEY(NU_TIPO_MODELO)
	REFERENCES CCR.CCRTB070_TIPO_MODELO(NU_TIPO_MODELO)
	 );

/*==============================================================*/
/* Table: CCRTB072_CAMPO                                        */
/*==============================================================*/
CREATE TABLE CCR.CCRTB072_CAMPO  ( 
	NU_CAMPO       	NUMBER(19) NOT NULL,
	NU_SISTEMA     	NUMBER(19) NULL,
	NO_CAMPO       	VARCHAR2(60) NOT NULL,
	DE_CAMPO       	VARCHAR2(255) NULL,
	DE_ORIGEM_CAMPO	VARCHAR2(255) NULL,
	NO_CAMPO_JAVA  	VARCHAR2(100) NULL,
	CONSTRAINT PK_CCRTB072 PRIMARY KEY(NU_CAMPO)
);



/*==============================================================*/
/* Table: CCRTB073_CAMPO_MODELO_CONTRATO                                  */
/*==============================================================*/

CREATE TABLE CCR.CCRTB073_CAMPO_MODELO_CONTRATO  ( 
	NU_MODELO     	NUMBER(19) NULL,
	NU_CAMPO      	NUMBER(19) NULL,
	CONSTRAINT PK_CCRTB073 PRIMARY KEY(NU_CAMPO, NU_MODELO)
);
ALTER TABLE CCR.CCRTB073_CAMPO_MODELO_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB073_CCRTB072
	FOREIGN KEY(NU_CAMPO)
	REFERENCES CCR.CCRTB072_CAMPO(NU_CAMPO)
	 );
ALTER TABLE CCR.CCRTB073_CAMPO_MODELO_CONTRATO
	ADD ( CONSTRAINT FK_CCRTB073_CCRTB071
	FOREIGN KEY(NU_MODELO)
	REFERENCES CCR.CCRTB071_MODELO_CONTRATO(NU_MODELO)
	 );


/*==============================================================*/
/* Table: CCRTB049_CONVENIO_CNPJ_VNCDO                        */
/*==============================================================*/
CREATE TABLE CCR.CCRTB049_CONVENIO_CNPJ_VNCDO  ( 
	NU_SEQUENCIAL_CONVENIO_CNPJ	NUMBER(19) NOT NULL,
	NU_CONVENIO                	NUMBER(5) NULL,
	NU_CNPJ                    	NUMBER(14) NOT NULL,
	CONSTRAINT PK_CCRTB049 PRIMARY KEY(NU_SEQUENCIAL_CONVENIO_CNPJ)
);
ALTER TABLE CCR.CCRTB049_CONVENIO_CNPJ_VNCDO
	ADD ( CONSTRAINT FK_CCRTB049_CCRTB001_1
	FOREIGN KEY(NU_CONVENIO)
	REFERENCES CCR.CCRTB001_CONVENIO(NU_CONVENIO)
);



/*==============================================================*/
/* Table: CCRTBH13_CONTRATO                                     */
/*==============================================================*/
CREATE TABLE CCR.CCRTBH13_CONTRATO  ( 
	NU_HISTORICO_CONTRATO      	NUMBER(19) NOT NULL,
	NU_CONTRATO                	NUMBER(19) NOT NULL,
	NU_UNIDADE_MOVIMENTO       	NUMBER(19) NOT NULL,
	NU_NATURAL_MOVIMENTO       	NUMBER(19) NOT NULL,
	NU_CPF                     	NUMBER(11) NOT NULL,
	NU_COCLI                   	NUMBER(19) NOT NULL,
	NU_RIC                     	NUMBER(15) NULL,
	NU_BENEFICIO               	NUMBER(8) NULL,
	NU_CONTRATO_APLICACAO      	NUMBER(19) NOT NULL,
	VR_LIQUIDO_CONTRATO        	NUMBER(11,2) NOT NULL,
	VR_PRESTACAO               	NUMBER(8,2) NOT NULL,
	PZ_CONTRATO                	NUMBER(4) NOT NULL,
	VR_CONTRATO                	NUMBER(11,2) NOT NULL,
	DT_LIBERACAO_CREDITO       	DATE NOT NULL,
	VR_IOF                     	NUMBER(8,2) NOT NULL,
	PC_TAXA_JURO_CONTRATO      	NUMBER(8,5) NOT NULL,
	PC_CET_MENSAL              	NUMBER(8,5) NOT NULL,
	PC_CET_ANUAL               	NUMBER(8,5) NOT NULL,
	DT_BASE_CALCULO            	DATE NOT NULL,
	DT_VNCMO_PRIMEIRA_PRESTACAO	DATE NOT NULL,
	QT_DIA_JURO_ACERTO         	NUMBER(6) NULL,
	VR_JURO_ACERTO             	NUMBER(8,2) NULL,
	VR_SEGURO_PRESTAMISTA      	NUMBER(11,2) NULL,
	PC_TAXA_SEGURO             	NUMBER(8,5) NOT NULL,
	NU_BANCO_CONTA_CREDITO     	NUMBER(4) NULL,
	NU_AGENCIA_CONTA_CREDITO   	NUMBER(5) NULL,
	NU_OPERACAO_CONTA_CREDITO  	NUMBER(3) NULL,
	NU_CONTA_CREDITO           	NUMBER(8) NULL,
	NU_DV_CONTA_CREDITO        	NUMBER(1) NULL,
	IC_TIPO_CREDITO            	NUMBER(1) NOT NULL,
	DT_CONTRATO                	DATE NOT NULL,
	PC_ALIQUOTA_BASICA         	NUMBER(8,5) NOT NULL,
	PC_ALIQUOTA_COMPLEMENTAR   	NUMBER(8,5) NOT NULL,
	NU_AVALIACAO               	NUMBER(19) NOT NULL,
	DT_SITUACAO                	DATE NULL,
	NU_SITUACAO                	NUMBER(5) NULL,
	NU_TIPO_SITUACAO           	NUMBER(5) NULL,
	NU_CONVENIO                	NUMBER(5) NULL,
	NU_BANCO_CONTA_DEBITO      	NUMBER(4) NULL,
	NU_AGENCIA_CONTA_DEBITO    	NUMBER(5) NULL,
	NU_OPERACAO_CONTA_DEBITO   	NUMBER(3) NULL,
	NU_CONTA_DEBITO            	NUMBER(8) NULL,
	NU_DV_CONTA_DEBITO         	NUMBER(1) NULL,
	VR_CET_MENSAL              	NUMBER(8,5) NULL,
	VR_CET_ANUAL               	NUMBER(8,5) NULL,
	PC_CET_JURO_ACERTO         	NUMBER(8,5) NULL,
	PC_CET_CAPITAL             	NUMBER(8,5) NULL,
	PC_CET_IOF                 	NUMBER(8,5) NULL,
	PC_CET_SEGURO              	NUMBER(8,5) NULL,
	VR_BRUTO_BENEFICIO         	NUMBER(15,2) NULL,
	VR_LIQUIDO_BENEFICIO       	NUMBER(15,2) NULL,
	PC_TAXA_JURO_ANUAL         	NUMBER(8,5) NULL,
	IC_EMPREGADO_TEMPORARIO    	CHAR(1) NULL,
	CO_USUARIO                 	CHAR(8) NULL,
	DT_VENCIMENTO              	DATE NULL,
	IC_SEGURO_PRESTAMISTA      	CHAR(1) NULL,
	DT_COMPETENCIA             	DATE NULL,
	IC_RECEBE_SALARIO_CAIXA    	CHAR(1) NULL,
	CO_TIPO_SIMULACAO          	CHAR(1) NULL,
	NU_ORGAO_MILITAR           	NUMBER(6) NULL,
	QT_EMPREGADO               	NUMBER(5) NULL,
	DD_BENEFICIO               	NUMBER(2) NULL,
	NU_CNPJ_FONTE_PAGADORA     	NUMBER(14) NULL,
	VR_TOTAL_CONTRATO          	NUMBER(11,2) NULL,
	CO_MATRICULA_CLIENTE       	VARCHAR2(100) NULL,
	IC_ACAO                    	CHAR(1) NULL,
	TS_HISTORICO               	CHAR(10) NULL,
	NU_AGENCIA_CONCESSORA      	NUMBER(5) NULL,
	DD_VENCIMENTO_PRESTACAO    	NUMBER(2) NULL,
	CONSTRAINT PK_CCRTBH13 PRIMARY KEY(NU_HISTORICO_CONTRATO)
);
ALTER TABLE CCR.CCRTBH13_CONTRATO
	ADD ( CONSTRAINT CC_CCRTBH13_2
	CHECK (CO_TIPO_SIMULACAO is null or (CO_TIPO_SIMULACAO in ('P','V')))
	 );
ALTER TABLE CCR.CCRTBH13_CONTRATO
	ADD ( CONSTRAINT CC_CCRTBH13_1
	CHECK (IC_RECEBE_SALARIO_CAIXA is null or (IC_RECEBE_SALARIO_CAIXA in ('S','N')))
	 );




