INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(408, 403, 'ANITA GARIBALDI, SC                ', 'SC', 8, 'AT', '     ', 1, 3603050408, 31);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(739, 714, 'TOBIAS BARRETO, SE                 ', 'SE', 8, 'AT', '     ', 0, 3603050739, 26);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(409, 404, 'NEWTON MACUCO, SC                  ', 'SC', 8, 'AT', '     ', 0, 3603050409, 12);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(132, 132, 'MONTES CLAROS, MG                  ', 'MG', 8, 'AT', '     ', 5, 3603050132, 73);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(740, 715, 'PORTO FERREIRA, SP                 ', 'SP', 8, 'AT', '     ', 4, 3603050740, 60);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(181, 181, 'DUQUE DE CAXIAS, RJ                ', 'RJ', 8, 'AT', '     ', 3, 3603050181, 51);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(412, 407, 'BRUSQUE, SC                        ', 'SC', 8, 'AT', '     ', 0, 3603050412, 18);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(410, 405, 'HERIBERTO HULSE, SC                ', 'SC', 8, 'AT', '     ', 3, 3603050410, 56);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(133, 133, 'MURIAE, MG                         ', 'MG', 8, 'AT', '     ', 3, 3603050133, 54);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(741, 716, 'PEDREIRA, SP                       ', 'SP', 8, 'AT', '     ', 2, 3603050741, 40);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(180, 180, 'CAMPOS, RJ                         ', 'RJ', 8, 'AT', '     ', 5, 3603050180, 70);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(407, 402, 'UNIAO DA VITORIA, PR               ', 'PR', 8, 'AT', '     ', 3, 3603050407, 50);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(738, 713, 'BARUERI, SP                        ', 'SP', 8, 'AT', '     ', 2, 3603050738, 45);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(138, 138, 'PARACATU, MG                       ', 'MG', 8, 'AT', '     ', 4, 3603050138, 69);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(724, 701, 'IVAIPORA, PR                       ', 'PR', 8, 'AT', '     ', 2, 3603050724, 40);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(177, 177, 'BARRA DO PIRAI, RJ                 ', 'RJ', 8, 'AT', '     ', 5, 3603050177, 75);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(709, 686, 'MONTE CARMELO, MG                  ', 'MG', 8, 'AT', '     ', 9, 3603050709, 0);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(723, 700, 'IPORA, PR                          ', 'PR', 8, 'AT', '     ', 4, 3603050723, 69);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(4395, 7529, 'PINEVILLE, PR                      ', 'PR', 8, 'AT', '     ', 8, 3603054395, 5);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(175, 175, 'ICARAI, RJ                         ', 'RJ', 8, 'AT', '     ', 9, 3603050175, 3);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(405, 400, 'SANTO ANTONIO DA PLATINA, PR       ', 'PR', 8, 'AT', '     ', 7, 3603050405, 99);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(677, 656, 'ANTONIO DE GODOY                   ', 'SP', 8, 'EN', '     ', 7, 3603050677, 99);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(416, 411, 'ITAJAI, SC                         ', 'SC', 8, 'AT', '     ', 2, 3603050416, 41);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(406, 401, 'SAO JOSE DOS PINHAIS, PR           ', 'PR', 8, 'AT', '     ', 5, 3603050406, 70);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(131, 131, 'MANHUACU, MG                       ', 'MG', 8, 'AT', '     ', 7, 3603050131, 92);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(680, 658, 'REALENGO, RJ                       ', 'RJ', 8, 'AT', '     ', 7, 3603050680, 94);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(401, 396, 'PRUDENTOPOLIS, PR                  ', 'PR', 8, 'AT', '     ', 4, 3603050401, 65);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(183, 183, 'MAGE, RJ                           ', 'RJ', 8, 'AT', '     ', 0, 3603050183, 13);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(728, 705, 'SAO RAIMUNDO NONATO, PI            ', 'PI', 8, 'AT', '     ', 5, 3603050728, 73);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(413, 408, 'CANOINHAS, SC                      ', 'SC', 8, 'AT', '     ', 8, 3603050413, 7);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(727, 704, 'VALENCA DO PIAUI                   ', 'PI', 8, 'EN', '     ', 7, 3603050727, 92);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(708, 685, 'IBIA, MG                           ', 'MG', 8, 'AT', '     ', 0, 3603050708, 20);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(411, 406, 'BLUMENAU, SC                       ', 'SC', 8, 'AT', '     ', 1, 3603050411, 37);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(716, 693, 'MONTANHA, ES                       ', 'ES', 8, 'AT', '     ', 1, 3603050716, 30);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(130, 130, 'CATEDRAL                           ', 'MG', 8, 'EN', '     ', 9, 3603050130, 1);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(791, 766, 'FORMOSA, GO                        ', 'GO', 8, 'AT', '     ', 9, 3603050791, 0);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(402, 397, 'RIBEIRAO CLARO, PR                 ', 'PR', 8, 'AT', '     ', 2, 3603050402, 46);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(184, 184, 'MACAE, RJ                          ', 'RJ', 8, 'AT', '     ', 8, 3603050184, 2);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(789, 764, 'GUIRATINGA                         ', 'MT', 8, 'EN', '     ', 7, 3603050789, 95);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(414, 409, 'CHAPECO, SC                        ', 'SC', 8, 'AT', '     ', 6, 3603050414, 80);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(404, 399, 'ROLANDIA, PR                       ', 'PR', 8, 'AT', '     ', 9, 3603050404, 8);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(733, 709, 'ITABAIANA DO NORTE, PB             ', 'PB', 8, 'AT', '     ', 1, 3603050733, 30);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(678, 657, 'CIDADE UNIVERSITARIA, PE           ', 'PE', 8, 'AT', '     ', 5, 3603050678, 70);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(148, 148, 'SANTANA DO JACARE, MG              ', 'MG', 8, 'AT', '     ', 1, 3603050148, 30);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(168, 168, 'ENSEADA, ES                        ', 'ES', 8, 'AT', '     ', 6, 3603050168, 84);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(424, 419, 'SAO FRANCISCO DO SUL, SC           ', 'SC', 8, 'AT', '     ', 3, 3603050424, 51);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(403, 398, 'RIO NEGRO, PR                      ', 'PR', 8, 'AT', '     ', 0, 3603050403, 27);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(732, 708, 'POMBAL, PB                         ', 'PB', 8, 'AT', '     ', 3, 3603050732, 50);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(173, 173, 'VILA VELHA, ES                     ', 'ES', 8, 'AT', '     ', 2, 3603050173, 41);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(721, 698, 'SAO GABRIEL DA PALHA, ES           ', 'ES', 8, 'AT', '     ', 8, 3603050721, 5);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(421, 416, 'LAGUNA, SC                         ', 'SC', 8, 'AT', NULL, 9, 3603050421, 9);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(382, 377, 'BANDEIRANTES, PR                   ', 'PR', 8, 'AT', '     ', 4, 3603050382, 68);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(174, 174, 'NITEROI, RJ                        ', 'RJ', 8, 'AT', '     ', 0, 3603050174, 22);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(793, 768, 'GURUPI, TO                         ', 'TO', 8, 'AT', '     ', 5, 3603050793, 71);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(722, 699, 'GUAIRA, PR                         ', 'PR', 8, 'AT', '     ', 6, 3603050722, 88);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(419, 414, 'JOINVILLE, SC                      ', 'SC', 8, 'AT', '     ', 7, 3603050419, 94);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(134, 134, 'NOVA LIMA, MG                      ', 'MG', 8, 'AT', '     ', 1, 3603050134, 35);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(4515, 7533, 'NOVA AMERICA, RJ                   ', 'RJ', 8, 'AT', '     ', 2, 3603054515, 48);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(178, 178, 'BOM JESUS DO ITABAPOANA, RJ        ', 'RJ', 8, 'AT', '     ', 3, 3603050178, 56);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(384, 379, 'CAMBE, PR                          ', 'PR', 8, 'AT', '     ', 0, 3603050384, 20);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(743, 718, 'ARACATI, CE                        ', 'CE', 8, 'AT', '     ', 9, 3603050743, 2);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(736, 711, 'ITAPORANGA                         ', 'SP', 8, 'EN', '     ', 6, 3603050736, 83);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(142, 142, 'PATOS DE MINAS, MG                 ', 'MG', 8, 'AT', '     ', 2, 3603050142, 45);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(136, 136, 'OURO PRETO, MG                     ', 'MG', 8, 'AT', '     ', 8, 3603050136, 5);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(422, 417, 'PORTO UNIAO, SC                    ', 'SC', 8, 'AT', '     ', 7, 3603050422, 90);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(383, 378, 'CAMBARA, PR                        ', 'PR', 8, 'AT', '     ', 2, 3603050383, 49);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(171, 171, 'CACHOEIRO DE ITAPEMIRIM, ES        ', 'ES', 8, 'AT', '     ', 6, 3603050171, 80);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(737, 712, 'BORBOREMA, PB                      ', 'PB', 8, 'AT', '     ', 4, 3603050737, 64);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(4456, 7531, 'MONSENHOR FELIX, RJ                ', 'RJ', 8, 'AT', '     ', 3, 3603054456, 53);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(746, 721, 'CANINDE, CE                        ', 'CE', 8, 'AT', '     ', 3, 3603050746, 55);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(141, 141, 'PASSOS, MG                         ', 'MG', 8, 'AT', '     ', 4, 3603050141, 64);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(179, 179, 'CABO FRIO, RJ                      ', 'RJ', 8, 'AT', '     ', 1, 3603050179, 37);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(415, 410, 'CRICIUMA, SC                       ', 'SC', 8, 'AT', '     ', 4, 3603050415, 60);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(139, 139, 'PARAGUACU, MG                      ', 'MG', 8, 'AT', '     ', 2, 3603050139, 40);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(418, 413, 'JOACABA, SC                        ', 'SC', 8, 'AT', '     ', 9, 3603050418, 3);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(143, 143, 'PATROCINIO, MG                     ', 'MG', 8, 'AT', '     ', 0, 3603050143, 26);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(137, 137, 'PARA DE MINAS, MG                  ', 'MG', 8, 'AT', '     ', 6, 3603050137, 88);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(695, 672, 'SANTO AUGUSTO, RS                  ', 'RS', 8, 'AT', '     ', 5, 3603050695, 70);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(689, 667, 'CONSOLACAO, SP                     ', 'SP', 8, 'AT', '     ', 0, 3603050689, 22);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(400, 395, 'PONTA GROSSA, PR                   ', 'PR', 8, 'AT', '     ', 6, 3603050400, 84);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(693, 670, 'SANTA VITORIA DO PALMAR, RS        ', 'RS', 8, 'AT', '     ', 9, 3603050693, 9);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(3893, 7532, 'CANINDE DE SAO FRANCISCO, SE       ', 'SE', 8, 'AT', '     ', 8, 3603053893, 3);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(387, 382, 'CASTRO, PR                         ', 'PR', 8, 'AT', '     ', 5, 3603050387, 72);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(692, 669, 'CANELA, RS                         ', 'RS', 8, 'AT', '     ', 0, 3603050692, 28);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(172, 172, 'COLATINA, ES                       ', 'ES', 8, 'AT', '     ', 4, 3603050172, 60);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(420, 415, 'LAGES, SC                          ', 'SC', 8, 'AT', '     ', 0, 3603050420, 28);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(691, 668, 'MACHADO, MG                        ', 'MG', 8, 'AT', '     ', 2, 3603050691, 47);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(696, 673, 'SAO SEBASTIAO DO CAI, RS           ', 'RS', 8, 'AT', '     ', 3, 3603050696, 51);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(385, 380, 'CAMPO LARGO, PR                    ', 'PR', 8, 'AT', '     ', 9, 3603050385, 0);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(4392, 7534, 'BELO ORIENTE, MG                   ', 'MG', 8, 'AT', '     ', 3, 3603054392, 54);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(417, 412, 'JARAGUA DO SUL, SC                 ', 'SC', 8, 'AT', '     ', 0, 3603050417, 22);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(386, 381, 'CAMPO MOURAO, PR                   ', 'PR', 8, 'AT', '     ', 7, 3603050386, 91);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(697, 674, 'MARAU, RS                          ', 'RS', 8, 'AT', '     ', 1, 3603050697, 32);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(4355, 7535, 'NAZARE PAULISTA, SP                ', 'SP', 8, 'AT', '     ', 9, 3603054355, 0);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(362, 357, 'TUPA, SP                           ', 'SP', 8, 'AT', '     ', 0, 3603050362, 14);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(156, 156, 'TRES CORACOES, MG                  ', 'MG', 8, 'AT', '     ', 2, 3603050156, 40);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(704, 681, 'AIMORES, MG                        ', 'MG', 8, 'AT', '     ', 8, 3603050704, 4);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(683, 661, 'MARABA, PA                         ', 'PA', 8, 'AT', '     ', 1, 3603050683, 37);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(620, 604, 'JUSTICA TRABALHO BELO HORIZONTE, MG', 'MG', 56, 'AT', '     ', 3, 3603050620, 53);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(609, 593, 'PIRAPORA, MG                       ', 'MG', 8, 'AT', '     ', 2, 3603050609, 48);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(614, 598, 'RONDONOPOLIS, MT                   ', 'MT', 8, 'AT', '     ', 9, 3603050614, 5);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(5034, 6646, 'SEGMENTO DE SEGUROS                ', 'DF', 22, 'EN', 'SUNSE', 2, 3603050001, 4);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(622, 606, 'DELEGACIA MINISTERIO DA FAZENDA    ', 'PE', 9, 'EN', '     ', 0, 3603050622, 15);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(681, 659, 'MANGABEIRAS, MG                    ', 'MG', 8, 'AT', '     ', 5, 3603050681, 75);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(613, 597, 'IGUATU, CE                         ', 'CE', 8, 'AT', '     ', 0, 3603050613, 24);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(3842, 7460, 'SAO MIGUEL DO IGUACU, PR           ', 'PR', 8, 'AT', '     ', 3, 3603053842, 55);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(4206, 7457, 'CERQUEIRA CESAR, SP                ', 'SP', 8, 'AT', '     ', 4, 3603054206, 69);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(363, 358, 'VALINHOS, SP                       ', 'SP', 8, 'AT', '     ', 8, 3603050363, 3);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(703, 680, 'SANTO ANTONIO DA PATRULHA, RS      ', 'RS', 8, 'AT', '     ', 0, 3603050703, 15);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(619, 603, 'DEL PASEO, CE                      ', 'CE', 8, 'AT', '     ', 0, 3603050619, 10);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(162, 162, 'TUBAL VILELA, MG                   ', 'MG', 8, 'AT', '     ', 7, 3603050162, 99);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(615, 599, 'AQUIDAUANA, MS                     ', 'MS', 8, 'AT', '     ', 7, 3603050615, 96);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(5033, 6645, 'NEGOCIOS COM CARTOES               ', 'DF', 22, 'EN', 'SUCAR', 4, 3603050001, 4);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(157, 157, 'TRES PONTAS, MG                    ', 'MG', 8, 'AT', '     ', 0, 3603050157, 21);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(365, 360, 'VICENTE DE CARVALHO, SP            ', 'SP', 8, 'AT', '     ', 4, 3603050365, 67);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(684, 662, 'CRATO, CE                          ', 'CE', 8, 'AT', '     ', 0, 3603050684, 18);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(694, 671, 'ANDRADAS, MG                       ', 'MG', 8, 'AT', '     ', 7, 3603050694, 90);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(706, 683, 'CONSELHEIRO PENA, MG               ', 'MG', 8, 'AT', '     ', 4, 3603050706, 68);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(158, 158, 'TUPACIGUARA, MG                    ', 'MG', 8, 'AT', '     ', 9, 3603050158, 2);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(364, 359, 'VOTUPORANGA, SP                    ', 'SP', 8, 'AT', '     ', 6, 3603050364, 86);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(707, 684, 'GUANHAES, MG                       ', 'MG', 8, 'AT', '     ', 2, 3603050707, 49);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(618, 602, 'LIBERDADE, BA                      ', 'BA', 8, 'AT', '     ', 1, 3603050618, 39);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(3400, 6644, 'PREFEITURA MUNICIPAL JOANOPOLIS, SP', 'SP', 9, 'EN', '     ', 2, 3603053400, 45);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(617, 601, 'MINISTRO JOSE AMERICO, PB          ', 'PB', 8, 'AT', '     ', 3, 3603050617, 58);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(744, 719, 'BREJO SANTO, CE                    ', 'CE', 8, 'AT', '     ', 7, 3603050744, 93);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(720, 697, 'CIDADE DE PINHEIROS                ', 'ES', 8, 'EN', '     ', 0, 3603050720, 16);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(624, 608, 'BASE AEREA CANOAS                  ', 'RS', 9, 'EN', '     ', 6, 3603050624, 87);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(4331, 7539, 'RECANTO DAS EMAS, DF               ', 'DF', 8, 'AT', '     ', 1, 3603054331, 32);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(371, 366, 'BACACHERI, PR                      ', 'PR', 8, 'AT', '     ', 9, 3603050371, 5);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(3400, 6651, 'JOANOPOLIS, SP                     ', 'SP', 56, 'AT', '     ', 2, 3603053400, 45);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(742, 717, 'ITANHAEM, SP                       ', 'SP', 8, 'AT', '     ', 0, 3603050742, 21);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(144, 144, 'PEDRO LEOPOLDO, MG                 ', 'MG', 8, 'AT', '     ', 9, 3603050144, 7);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(3405, 6650, 'GOIANIRA, GO                       ', 'GO', 8, 'AT', '     ', 3, 3603053405, 50);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(159, 159, 'UBA, MG                            ', 'MG', 8, 'AT', '     ', 7, 3603050159, 93);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(368, 363, 'COMENDADOR, PR                     ', 'PR', 8, 'AT', '     ', 9, 3603050368, 0);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(612, 596, 'BROOKLIN, SP                       ', 'SP', 8, 'AT', '     ', 2, 3603050612, 43);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(623, 607, 'PRAIA DE BELAS, RS                 ', 'RS', 8, 'AT', '     ', 8, 3603050623, 4);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(611, 595, 'MORRINHOS, GO                      ', 'GO', 8, 'AT', '     ', 4, 3603050611, 62);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(366, 361, 'BOQUEIRAO, SP                      ', 'SP', 8, 'AT', '     ', 2, 3603050366, 48);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(610, 594, 'ARAGUAINA, TO                      ', 'TO', 8, 'AT', '     ', 6, 3603050610, 81);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(5124, 6652, 'FINANCEIRO                         ', 'DF', 41, 'FE', 'PEFIN', 1, 3603050001, 4);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(625, 609, 'JUSTICA FEDERAL RIO DE JANEIRO, RJ ', 'RJ', 56, 'AT', '     ', 4, 3603050625, 68);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(161, 161, 'UBERLANDIA, MG                     ', 'MG', 8, 'AT', '     ', 9, 3603050161, 8);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(170, 170, 'AFONSO CLAUDIO, ES                 ', 'ES', 8, 'AT', '     ', 8, 3603050170, 7);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(423, 418, 'RIO DO SUL, SC                     ', 'SC', 8, 'AT', '     ', 5, 3603050423, 70);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(626, 610, 'VITORIA DE SANTO ANTAO, PE         ', 'PE', 8, 'AT', '     ', 2, 3603050626, 49);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(792, 767, 'GOIANESIA, GO                      ', 'GO', 8, 'AT', '     ', 7, 3603050792, 90);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(745, 720, 'CAMOCIM, CE                        ', 'CE', 8, 'AT', '     ', 5, 3603050745, 74);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(3342, 6643, 'BARREIRINHA, PR                    ', 'PR', 8, 'AT', '     ', 1, 3603053342, 31);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(367, 362, 'ALEM PONTE, SP                     ', 'SP', 8, 'AT', '     ', 0, 3603050367, 29);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(381, 376, 'ARAUCARIA, PR                      ', 'PR', 8, 'AT', '     ', 6, 3603050381, 87);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(147, 147, 'POUSO ALEGRE, MG                   ', 'MG', 8, 'AT', '     ', 3, 3603050147, 50);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(426, 421, 'SIDEROPOLIS, SC                    ', 'SC', 8, 'AT', '     ', 0, 3603050426, 13);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(608, 592, 'LEOPOLDINA, MG                     ', 'MG', 8, 'AT', '     ', 4, 3603050608, 67);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(701, 678, 'XANXERE, SC                        ', 'SC', 8, 'AT', '     ', 3, 3603050701, 53);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(688, 666, 'NUCLEO BANDEIRANTE, DF             ', 'DF', 8, 'AT', '     ', 2, 3603050688, 41);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(167, 167, 'BEIRAMAR, ES                       ', 'ES', 8, 'AT', '     ', 8, 3603050167, 1);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(710, 687, 'RAUL SOARES, MG                    ', 'MG', 8, 'AT', '     ', 2, 3603050710, 44);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(702, 679, 'SAO MIGUEL DO OESTE, SC            ', 'SC', 8, 'AT', '     ', 1, 3603050702, 34);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(164, 164, 'VICOSA, MG                         ', 'MG', 8, 'AT', '     ', 3, 3603050164, 50);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(146, 146, 'PONTE NOVA, MG                     ', 'MG', 8, 'AT', '     ', 5, 3603050146, 79);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(380, 375, 'ARAPONGAS, PR                      ', 'PR', 8, 'AT', '     ', 8, 3603050380, 4);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(713, 690, 'QUILOMBO DOS PALMARES, AL          ', 'AL', 8, 'AT', '     ', 7, 3603050713, 97);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(425, 420, 'TUBARAO, SC                        ', 'SC', 8, 'AT', '     ', 1, 3603050425, 32);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(169, 169, 'ALEGRE, ES                         ', 'ES', 8, 'AT', '     ', 4, 3603050169, 65);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(699, 676, 'PIRIPIRI, PI                       ', 'PI', 8, 'AT', '     ', 8, 3603050699, 2);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(687, 665, 'PAB ESTIVADORES SANT               ', 'SP', 9, 'EN', '     ', 4, 3603050687, 60);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(711, 688, 'RIO LARGO, AL                      ', 'AL', 8, 'AT', '     ', 0, 3603050711, 25);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(160, 160, 'UBERABA, MG                        ', 'MG', 8, 'AT', NULL, 0, 3603050160, 27);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(376, 371, 'SANTA FELICIDADE, PR               ', 'PR', 8, 'AT', '     ', 0, 3603050376, 10);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(378, 373, 'ANTONINA, PR                       ', 'PR', 8, 'AT', '     ', 6, 3603050378, 81);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(698, 675, 'SERAFINA CORREA, RS                ', 'RS', 8, 'AT', '     ', 0, 3603050698, 13);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(729, 706, 'MANAIRA SHOPPING, PB               ', 'PB', 8, 'AT', '     ', 3, 3603050729, 54);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(430, 425, 'RUA DA PRAIA, RS                   ', 'RS', 8, 'AT', '     ', 8, 3603050430, 8);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(372, 367, 'CRISTO REI, PR                     ', 'PR', 8, 'AT', '     ', 7, 3603050372, 96);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(166, 166, 'VISCONDE DO RIO BRANCO, MG         ', 'MG', 8, 'AT', '     ', 0, 3603050166, 12);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(719, 696, 'BARRA DE SAO FRANCISCO, ES         ', 'ES', 8, 'AT', '     ', 6, 3603050719, 82);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(165, 165, 'VIRGINIA, MG                       ', 'MG', 8, 'AT', '     ', 1, 3603050165, 31);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(427, 422, 'ARARANGUA, SC                      ', 'SC', 8, 'AT', '     ', 8, 3603050427, 2);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(718, 695, 'BAIXO GUANDU, ES                   ', 'ES', 8, 'AT', '     ', 8, 3603050718, 0);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(373, 368, 'MARECHAL DEODORO, PR               ', 'PR', 8, 'AT', '     ', 5, 3603050373, 77);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(725, 702, 'TELEMACO BORBA, PR                 ', 'PR', 8, 'AT', '     ', 0, 3603050725, 20);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(730, 707, 'CATOLE DO ROCHA                    ', 'PB', 8, 'EN', '     ', 7, 3603050730, 98);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(5084, 6649, 'INOVACAO DO NEGOCIO                ', 'DF', 23, 'FE', 'GEICV', 9, 3603050001, 4);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(682, 660, 'JUSTICA FEDERAL GOIANIA, GO        ', 'GO', 56, 'AT', '     ', 3, 3603050682, 56);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(607, 591, 'JOAO MONLEVADE, MG                 ', 'MG', 8, 'AT', '     ', 6, 3603050607, 86);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(186, 186, 'NOVA FRIBURGO, RJ                  ', 'RJ', 8, 'AT', '     ', 4, 3603050186, 66);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(375, 370, 'PORTAO, PR                         ', 'PR', 8, 'AT', '     ', 1, 3603050375, 39);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(428, 423, 'PRACA DA ALFANDEGA, RS             ', 'RS', 8, 'AT', '     ', 6, 3603050428, 85);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(188, 188, 'PETROPOLIS, RJ                     ', 'RJ', 8, 'AT', '     ', 0, 3603050188, 28);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(726, 703, 'TOLEDO, PR                         ', 'PR', 8, 'AT', '     ', 9, 3603050726, 1);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(685, 663, 'DNOCS, CE                          ', 'CE', 56, 'AT', NULL, 8, 3603050685, 7);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(149, 149, 'SANTOS DUMONT, MG                  ', 'MG', 8, 'AT', '     ', 0, 3603050149, 11);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(189, 189, 'RESENDE, RJ                        ', 'RJ', 8, 'AT', '     ', 9, 3603050189, 9);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(717, 694, 'SAO MATEUS, ES                     ', 'ES', 8, 'AT', '     ', 0, 3603050717, 10);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(185, 185, 'NOVA IGUACU, RJ                    ', 'RJ', 8, 'AT', '     ', 6, 3603050185, 85);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(150, 150, 'SAO GONCALO DO SAPUCAI, MG         ', 'MG', 8, 'AT', '     ', 3, 3603050150, 55);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(686, 664, 'UFMT, MT                           ', 'MT', 8, 'AT', '     ', 6, 3603050686, 80);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(374, 369, 'MERCES, PR                         ', 'PR', 8, 'AT', '     ', 3, 3603050374, 58);
INSERT INTO CCR.CCRVW001_UNIDADE
(NU_UNIDADE, NU_NATURAL, NO_UNIDADE, SG_UF_L22, NU_TP_UNIDADE_U21, IC_ULTIMA_SITUACAO, SG_UNIDADE, NU_DV_NU_UNIDADE, NU_CGC_UNIDADE, NU_DV_CGC)
VALUES(163, 163, 'VARGINHA, MG                       ', 'MG', 8, 'AT', '     ', 5, 3603050163, 70);
