
INSERT INTO CCRTB102_PRCSO_ENVIO_CONTRATO  (NU_PROCESSO_ENVIO_CONTRATO, NO_PROCESSO_ENVIO_CONTRATO, DH_INICIO_PROCESSO, DH_FIM_PROCESSO, NU_INTERVALO) 
VALUES (CCRSQ102_PRCSO_ENVIO_CONTRATO.nextval, 'SIAPX', TO_TIMESTAMP ('20-Abr-02 18:00:00', 'DD-Mon-RR HH24:MI:SS'), TO_TIMESTAMP ('20-Abr-02 20:00:00', 'DD-Mon-RR HH24:MI:SS'), 20);
