<html>                                                                                                            
<head>                                                                                                            
<meta charset='utf-8'>                                                                                            
<title>Extrato Mensal Cotista</title>                                                                             
</head>                                                                                                           
	<style>                                                                                                         
		p {line-height: 3px; padding-left: 20px; padding-right:10px; font-family: calibry, sans-serif}              
		table {width: 100%; text-align: left;margin-bottom:-5px;font-family: calibry, sans-serif}                   
		.tb_1 {font-size:12px;line-height: 8px; margin-left:16px;}                                                  
		.th_prc {padding-bottom:10px;text-align:center;padding-right:50px;}                                          
		.resultado {text-align: right !important; font-size:12px;}
		.tbl_p {font-size:12px;}  
		#logo {
          width: 115px;
          height: 25px;
          display: block;
          margin: 0 auto;
          float: left;
          margin-top: 10px;
          margin-left: 20px;
          margin-right: -40px;
    	}                                                                
	</style>                                                                                                        
	<div style='width: 90%; margin-left: 5%; margin-right: 5%; height: 643px;'>           
		<div style='border: 1px solid #000;height:50px;'>
			<div id="logo">
				<img src="data:image/png;base64,
				          iVBORw0KGgoAAAANSUhEUgAAAHoAAAAiCAYAAACQhM1+AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
                          jwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAloSURBVHhe7VprcFVXFb6ltXaqtepI1dYqVUfH
                          +mx9TbU/1BkcxzpWHYvvFhERKLWllJZAB1qqBGRqmVqKPEIoBCjFMLSiCYG8IC8eeRECJYG8IDxC
                          Qh73htyb3Nzl/u7dO3fn3HX2PjfoDyf3m/kmMzl7rXPu+c7ae621t49SGBdICT1OkBJ6nCAl9DjB
                          NQt98kKAXj9ygZbnNtHT2ado0e4GermglbKrLlJjR78c5Q0nhK/j7X6qP8+z9mwfXegNytFmRCKx
                          Z3PzB1/NnVfl6BjOdQfpSEsPO95JN4RqVlDo6GIKVS51ZbB4GoUvlkoLHsPiBxw718feWxHXrw4O
                          SwszxiQ0HmK7EPfHa6rpg/ML6PpZe1ne/kwhPfhqFR1q7pGW7qho6qHbniqgD8wroIniL8f3zc2n
                          H62pkhZmNAkRTf7g64k3TsrRMdQI8W+ak8eOV1T+dlVflFZxBA9MJ/86n5WBzFtouHv0vZ149s2G
                          6DM676/z/U/m08bSc9LCjKSF3lLRTp9afJAV1o2r8luktTu+8ZcK1tbJd8zO8/QV/7vuMmuvc8k/
                          G+XoOLw+x6SFRdIihlDpHFZUJ/u330WRULe04tHhD7H35PibzGPSygzPQg+Il/vQuhr2ZjaWnDb/
                          sPIz3aydG4+29EpLd2D54Gx17q65JEfHgSmRG+vkhJn7KbtSzlTVadTHiOpkYOsdFBnoiNkYMGf7
                          CfaeHL+8rExameFJ6LPdA3T3cyXsjWxEBGIaNeH+lYdYWzeuLzkrLd2BaZmz1Yn1m8MPxXLDjdfp
                          +0MJ3beynAKVy4gyfVahA5snUiRgf+7L/kG6YTZ/T443P7aPuq8OSWt3WIXGNPKRBUXsTbwQ63Rw
                          yH2qLUsymsFHxRdvwwOvVLK2iljf/MGwHD0apy71szY6rxMR7ZtWSxkrvi3WM15cxeia3Htaejdj
                          1rZ69n4mFp3qktbusAr9xRdKWedeaZtavplkNINYR234tCWPsD3XT9eal6kbZuWS73fVdOfjWTSU
                          4aOwIBvVGTfR8JU66dWM8z1B9l42vuQhBzIK/cyuU6zjZPiTv1dLb4koFWs3Z2Pje0U2Ggjx0Qhg
                          FsKUxtkqIt8w4czlq6ydzusEfVNP05r0yURZQtS1DpEFwx2HpEc7fr/lOHsfGx/ZZP+QXIU+LWpg
                          zilHTJNYN5HcbBZZ+c831I5cm7fzbekxEfetMGe473w0j/0/eNhQsqFU42x0onyx4Rfa7+AZi+o7
                          RFQjoocFR4ncXiA92YH+AH8POzHr2uAq9K83HmOd6rzl8f30Vi2fRSKTvvWJ/Qm1qsLBxiusT0Vk
                          npMWFrPXwLUH3BObrYfOszY6M8vs9ScaKpytzlhUN9Dq9O9G1+o+GdVDrXukF28wRfM9fy4zJpcI
                          CMxiJrBCdwYG6UZDNCmaogpoEEkNoovD15aXsz7Bzz1fEu2S4UPhroOzt7knZIvfamRtdOJD8wL7
                          By+ieno1ffixHRTeIF7nRiHymR3S2hvaLWvzi/uaac+xDvaa4r4TndIbD1ZofO2cM52mKdmGQpEl
                          cj4Vn98Ty1C5a4qY9t3wywzzlIuSz2srtbVrkHwzSkU5VShY7M6H2+iFpQ8RNWVKS+/47Wt17HMq
                          ouSyCb0yr1l648EKPc1yYxCNhbHCFM0g8gPAFNHvEcuGW3n09eXmtf+Tzx6QI72hrWtAJI69VC5m
                          JzdWnOmh4gZ7meOELZrvWlQcHYe9A+66Ij5uE1ihbSUP+sGmrNcE1HycT0W0VxU+IQThxigiD3Ai
                          JGp29KO58YqTVx2Roz2gaQe1V2ZQe+3rgttYdtdl0LnaLGmQHKaKjJl7RkXVps2tN7d0PyuWOxNY
                          oT+zxFyDYurDlzgW2KI5PbdJjiT6arp57OqiNjkyDuxYcWN1oinhBYONWykgEiusu+h+Rf/qFFk2
                          yira7KMHnk6n2Vmt0tIbWsVMwT2fzpauWFexuq2Pva4ITVCHu0E8ZSJszQYQCY8JiHhEHLYLFWxr
                          M3ZrdKAG58YpTheZqhP/qjOvZeBf99sbDEPN2SNlEsR2Etl1VHzB+59cRb5HmmiCSMwu9pqzXx22
                          RG+KVusPhiPGchPMOX5Zjk4EK7QtkhT/IdYNDsi0P77oQHR/Wge6UZwfRbQlUbtiaxO809J6/cqy
                          cuk5Di+bGW4loUK4LWdEZI69SuTXfDR5froQuTlaZiEDn7nV22yBSOWeTeeX/lQW3ZbFu/j+3yqt
                          Qi/Lic+GTrBC27JWnT9YXRl9uahdkS1/56UjI9fQ+VLIf9sczWMh19D3svNT57KZAYTPF7HiKkZF
                          xrQtRH5wwRIpMgTIHfHvJaq99CmSpT4DOMEKvam8nXWUDJ0ioOjnxl0rixtG18Pfe/koO04Ry4Pb
                          fjbalf71E1iBwRGRxZr8s7QFMZFnotUaFxmckZW4pOjw0ogZC7HkuoEVul+sr+/+o7lXbKO+abC3
                          vpMd89+gs6Fvyy/uFR8ch+HOKvJvuJEVGMSGRRANERHJUxfNlSLnC5+jRVY0Jau/SmLGTIbY3my7
                          MiDvMhqs0ABOhXDOvPJh7eTDte6AmaifsLjUF7KuY1PWJW6yDF+pJ//Gm1mBFQfWi1e1yUdzn5sh
                          RG4h30yUcLzIIJogHP5X0azoln+4Cg1868XDrDMvxGFBIO+EPZrfJWYP1MwfSyseIRoFXvbBP780
                          3tD3clIlbffojl6kr4kCm25lxdUZgdDNO+nNqlbyTUNfOifBt5M4bOiEfaNkbzQJxe/X3wfeD5JV
                          brxO1VV0wig0Dgx4PUPlpDo+hMyRu64TWXp4OBJtdiiinOgbGDIePgRRP6rkB+fZuDFx5tCGg1pP
                          uL+d/FtuY4V1MlK5UBoRTZzn7Z04z3PhpA03TucXxOyHHAK/X38feD/bDts3a9y2hY1CK3g5luMk
                          4CXT5kokHWhXcnY60R4EbM+Jc16FJ2XG3VUtBLw+QVCOwYp5MRuJtQfPsv456t07LzPkK4XuTZeq
                          tl7WRidyKw6ehAZwvgov0u0EKBIBHBvCj1EJEmpATEP6FOTkG0cvRMe6AS1Czk7nq8WxDhlKK+66
                          4qQFNdTTL6I/EiYqmEKBrNupf9e9PLPvof6ddwuRn4r6dgJ1LZYNfKhuxLtSLUyccf/Q/EL2uRTR
                          kTSd/8LZPWzdcraKH00bfTpVwbPQKfx/IyX0OEFK6HGClNDjBCmhxwWI/gNZmYB2Ez3AYQAAAABJ
                          RU5ErkJggg==">
			</div>                                                           
			<p style='text-align:center; margin-right:100px; padding-top:7px;'>Extrato Mensal</p>                                       
		</div>                                                                                                      
		<div style='border: 1px solid #000;height:90px;'>           
			<p>Numero do contrat: ##NUM_CONTRATO##</p>                                                                                   
			<p>Data Vencimento: ##DIA_VENC_PRES##</p>                                                                                       
			<p>Nome Comvenio: ##N_DO_CONV##</p>                                                                                
		</div><br>                                                                                                  
		<div style='border: 1px solid #000;height:50px;'>                                                           
			<p>Valor do Empresto: ##VAL_LIQ##</p>                                                                               
			<p>CNPJ: </p>                                                                                     
		</div><br>                                                                                                  
		<div style='border: 1px solid #000;height:150px;'>                                                          
			<table class='table tb_1'>                                                                              
				<tr>                                                                                                
					<th style='padding-bottom: 10px !important;padding-top:5px;'><small>Gestor do Fundo</small></th>
					<th style='padding-bottom: 10px !important;padding-top:5px;'><small>Fundo</small></th>          
				</tr>                                                                                               
				<tr>                                                                                                
					<td style='font-size:16px !important;'>Caixa Econ&ocirc;mica Federeal</td>                      
					<td>FG-FIES</td>                                                                                
				</tr>                                                                                               
			</table>                                                                                                
			<p>CPF/CNPJ: 00.360.305/0001-04 CPF/CNPJ: 11604.264/0001-70</p>                                         
			<p>Endere&ccedil;o: SAUS QUADRA 3 - BLOCO E - 10 ANDAR - BRAS&Iacute;LIA - DF</p>
			<p>CEP: 70070-030</p>       
			<p>Telefone: 61-3521-8008</p>                                                                           
			<p>E-mail: gefus@caixa.gov.br</p>                                                                       
		</div><br>                                                                                                  
		                                                                                           
	</div><br><br>                                                                                                  
<html>                                                                                                            